// Code generated by MockGen. DO NOT EDIT.
// Source: unit5.go
//
// Generated by this command:
//
//	mockgen -source=unit5.go -destination=./mocks/unit/unit5.gomock.go
//

// Package mock_unit is a generated GoMock package.
package mock_unit

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrinter is a mock of Printer interface.
type MockPrinter struct {
	ctrl     *gomock.Controller
	recorder *MockPrinterMockRecorder
}

// MockPrinterMockRecorder is the mock recorder for MockPrinter.
type MockPrinterMockRecorder struct {
	mock *MockPrinter
}

// NewMockPrinter creates a new mock instance.
func NewMockPrinter(ctrl *gomock.Controller) *MockPrinter {
	mock := &MockPrinter{ctrl: ctrl}
	mock.recorder = &MockPrinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrinter) EXPECT() *MockPrinterMockRecorder {
	return m.recorder
}

// Print mocks base method.
func (m *MockPrinter) Print(arg0 []int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Print", arg0)
}

// Print indicates an expected call of Print.
func (mr *MockPrinterMockRecorder) Print(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Print", reflect.TypeOf((*MockPrinter)(nil).Print), arg0)
}
